In [1]:
#$conda activate py37
#(py37)$ jupyter notebook

In [2]:
# %config IPCompleter.greedy=True

In [3]:
#press [SHIFT] and [TAB] from within the method parentheses

### intellisense - works perfect!! -> excute in command line windows. : (py37) $ -> works perfect !!
# (py37) $pip3 install jupyter-tabnine
# (py37) $sudo jupyter nbextension install --py jupyter_tabnine

# (py37) $jupyter nbextension enable jupyter_tabnine --py
##### jupyter nbextension enable --py jupyter_tabnine ##instead above line excuted. 

# (py37) $jupyter serverextension enable --py jupyter_tabnine

#--> I installed in (py37) conda env.

# Data Loading, Storage,

In [4]:
import numpy as np
import pandas as pd
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

## Reading and Writing Data in Text Format
* pd.read_csv('examples/ex2.csv', names=names_list, index_col='message')
* convert text data into a DataFrame

|Category|Description|
|:-------|:----------|
|Indexing|Can treat one or more columns as the returned DataFrame, and whether to get column names from the file, the user, or not at all.|
|Type inference and data conversion|user-defined value conversions and custom list of missing value markers.|
|Datetime parsing|combining capability, including combining date and time information spread over multiple columns into a single column in the result|
|Iterating|iterating over chunks of very large files.|
|Unclean data issues|Skipping rows or a footer, comments, or other minor things like numeric data with thousands separated by commas.|

In [5]:
!cat examples/ex1.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [7]:
# use comma as default delimiter
df = pd.read_csv('examples/ex1.csv')
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [6]:
# use tab ( '\t' ) as default delimiter
pd.read_table('examples/ex1.csv', sep=',')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [8]:
!cat examples/ex2.csv

1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [15]:
pd.read_csv('examples/ex2.csv') #not as intended!

   1   2   3   4  hello
0  5   6   7   8  world
1  9  10  11  12    foo

In [9]:
pd.read_csv('examples/ex2.csv', header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [10]:
pd.read_csv('examples/ex2.csv', names=['a', 'b', 'c', 'd', 'message'])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [16]:
names = ['a', 'b', 'c', 'd', 'message']
pd.read_csv('examples/ex2.csv', names=names, index_col='message')

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [17]:
!cat examples/csv_mindex.csv #with header

key1,key2,value1,value2
one,a,1,2
one,b,3,4
one,c,5,6
one,d,7,8
two,a,9,10
two,b,11,12
two,c,13,14
two,d,15,16

In [18]:
parsed = pd.read_csv('examples/csv_mindex.csv',
                     index_col=['key1', 'key2'])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [19]:
#table might not have a fixed delimiter, using whitespace or some
# other pattern to separate fields, Consider a text file that looks like this:
list(open('examples/ex3.txt'))

['            A         B         C\n',
 'aaa -0.264438 -1.026059 -0.619500\n',
 'bbb  0.927272  0.302904 -0.032399\n',
 'ccc -0.264273 -0.386314 -0.217601\n',
 'ddd -0.871858 -0.348382  1.100491\n']

While you could do some munging by hand, the fields here are separated by **a variable amount of whitespace**. In these cases, you can pass a regular expression as a
delimiter for read_table . This can be expressed by the regular expression **\s+** , so we
have then:

In [20]:
result = pd.read_table('examples/ex3.txt', sep='\s+')
result

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [22]:
!cat examples/ex4.csv

# hey!
a,b,c,d,message
# just wanted to make things more difficult for you
# who reads CSV files with computers, anyway?
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [23]:
pd.read_csv('examples/ex4.csv', skiprows=[0, 2, 3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [24]:
!cat examples/ex5.csv

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

In [25]:
result = pd.read_csv('examples/ex5.csv')
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [26]:
pd.isnull(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

[Null value : None, NaN](https://jakevdp.github.io/PythonDataScienceHandbook/03.04-missing-values.html)

|Category|Description|
|:-------|:----------|
|isnull()| Generate a boolean mask indicating missing values|
|notnull()| Opposite of isnull()|
|dropna()| Return a filtered version of the data|
|fillna()| Return a copy of the data with missing values filled or imputed|

In [27]:
# The na_values option can take either a list or set of strings to consider missing
# values:
result = pd.read_csv('examples/ex5.csv', na_values=['NULL']) #NULL consists of NaN and None
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [31]:
!cat examples/ex51.csv

something,a,b,c,d,message
one,1,2,3,4,NULL
two,5,6,,8,world
three,9,10,11,12,foo

In [32]:
result2 = pd.read_csv('examples/ex51.csv', na_values=['NULL'])
result2

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [33]:
sentinels = {'message': ['foo', 'NA'], 'something': ['two']}
pd.read_csv('examples/ex5.csv', na_values=sentinels)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

#### read_csv/read_table function arguments
|Argument|Description|
|:-------|:----------|
|path|String indicating filesystem location, URL, or file-like object|
|sep or delimiter|Character sequence or regular expression to use to split fields in each row|
|header|Row number to use as column names; defaults to 0 (first row), but should be None if there is no
header row|
|index_col|Column numbers or names to use as the row index in the result; can be a single name/number or a list of them for a hierarchical index|
|names|List of column names for result, combine with header=None| 
|skiprows|Number of rows at beginning of file to ignore or list of row numbers (starting from 0) to skip.|
|na_values|Sequence of values to replace with NA.|
|comment|Character(s) to split comments off the end of lines.|
|parse_dates|Attempt to parse data to datetime ; False by default. If True , will attempt to parse all columns. Otherwise can specify a list of column numbers or name to parse. If element of list is tuple or list, will combine multiple columns together and parse to date (e.g., if date/time split across two columns).|
|keep_date_col|If joining columns to parse date, keep the joined columns; False by default.|
|converters|Dict containing column number of name mapping to functions (e.g., {'foo': f} would apply the function f to all values in the 'foo' column).|
|dayfirst|When parsing potentially ambiguous dates, treat as international format (e.g., 7/6/2012 -> June 7, 2012); False by default.|
|date_parser|Function to use to parse dates.|
|nrows|Number of rows to read from beginning of file.|
|iterator|Return a TextParser object for reading file piecemeal.|
|chunksize|For iteration, size of file chunks.|
|skip_footer|Number of lines to ignore at end of file.|
|verbose|Print various parser output information, like the number of missing values placed in non-numeric columns.|
|encoding|Text encoding for Unicode (e.g., 'utf-8' for UTF-8 encoded text).|
|squeeze|If the parsed data only contains one column, return a Series.|
|thousands|Separator for thousands (e.g., ',' or '.' ).|

### Reading Text Files in Pieces

In [34]:
pd.options.display.max_rows = 10 #pandas display settings more compact:(10 rows)

In [35]:
result = pd.read_csv('examples/ex6.csv')
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [47]:
print(result['key'].unique())
result['key']

['L' 'B' 'G' 'R' 'Q' 'U' 'K' 'S' '8' '1' 'P' 'J' 'E' 'A' 'F' 'H' 'W' 'C'
 'V' 'I' '6' 'Y' 'T' 'M' 'X' 'N' 'O' 'Z' '2' 'D' '7' '0' '4' '5' '3' '9']

0       L
1       B
2       G
3       R
4       Q
       ..
9995    L
9996    E
9997    K
9998    G
9999    0
Name: key, Length: 10000, dtype: object

In [62]:
#test 1 : count frequency
import numpy as np
a = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
print("Original array:")
print(a)
unique_elements, counts_elements = np.unique(a, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements)))

print("----------------------------------")
print(np.array(np.unique(a, return_counts=True)))
print("-----------.T---------------------")
print(np.array(np.unique(a, return_counts=True)).T)
print("==================================")
result_frequency = np.array(np.unique(a, return_counts=True)).T
print(type(result_frequency))
[f"value {x[0]}'s frequency is {x[1]}" for x in result_frequency]

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]
----------------------------------
[[10 20 30 40 50]
 [ 3  4  2  2  1]]
-----------.T---------------------
[[10  3]
 [20  4]
 [30  2]
 [40  2]
 [50  1]]
==================================
<class 'numpy.ndarray'>

["value 10's frequency is 3",
 "value 20's frequency is 4",
 "value 30's frequency is 2",
 "value 40's frequency is 2",
 "value 50's frequency is 1"]

####  sort 2-d array based on 2nd column : .argsort() : returns an numpy.array of indices that sort the given numpy.array
* arr[arr[:, 1].argsort()]

In [73]:
#test 2
test_arr2 = np.array(np.unique(result['key'], return_counts=True)).T
test_arr2

array([['0', 151],
       ['1', 146],
       ['2', 152],
       ['3', 162],
       ['4', 171],
       ['5', 157],
       ['6', 166],
       ['7', 164],
       ['8', 162],
       ['9', 150],
       ['A', 320],
       ['B', 302],
       ['C', 286],
       ['D', 320],
       ['E', 368],
       ['F', 335],
       ['G', 308],
       ['H', 330],
       ['I', 327],
       ['J', 337],
       ['K', 334],
       ['L', 346],
       ['M', 338],
       ['N', 306],
       ['O', 343],
       ['P', 324],
       ['Q', 340],
       ['R', 318],
       ['S', 308],
       ['T', 304],
       ['U', 326],
       ['V', 328],
       ['W', 305],
       ['X', 364],
       ['Y', 314],
       ['Z', 288]], dtype=object)

In [74]:
#test 2
test_arr2[test_arr2[:, 1].argsort()]

array([['1', 146],
       ['9', 150],
       ['0', 151],
       ['2', 152],
       ['5', 157],
       ['3', 162],
       ['8', 162],
       ['7', 164],
       ['6', 166],
       ['4', 171],
       ['C', 286],
       ['Z', 288],
       ['B', 302],
       ['T', 304],
       ['W', 305],
       ['N', 306],
       ['S', 308],
       ['G', 308],
       ['Y', 314],
       ['R', 318],
       ['A', 320],
       ['D', 320],
       ['P', 324],
       ['U', 326],
       ['I', 327],
       ['V', 328],
       ['H', 330],
       ['K', 334],
       ['F', 335],
       ['J', 337],
       ['M', 338],
       ['Q', 340],
       ['O', 343],
       ['L', 346],
       ['X', 364],
       ['E', 368]], dtype=object)

In [82]:
#test2-2
n = len(test_arr2)
print(n)
test_arr2[test_arr2[:, 1].argsort()][::-1] #reverse order

36

array([['E', 368],
       ['X', 364],
       ['L', 346],
       ['O', 343],
       ['Q', 340],
       ['M', 338],
       ['J', 337],
       ['F', 335],
       ['K', 334],
       ['H', 330],
       ['V', 328],
       ['I', 327],
       ['U', 326],
       ['P', 324],
       ['D', 320],
       ['A', 320],
       ['R', 318],
       ['Y', 314],
       ['G', 308],
       ['S', 308],
       ['N', 306],
       ['W', 305],
       ['T', 304],
       ['B', 302],
       ['Z', 288],
       ['C', 286],
       ['4', 171],
       ['6', 166],
       ['7', 164],
       ['8', 162],
       ['3', 162],
       ['5', 157],
       ['2', 152],
       ['0', 151],
       ['9', 150],
       ['1', 146]], dtype=object)

In [68]:
#test 3 
result['key'].value_counts()

E    368
X    364
L    346
O    343
Q    340
    ...
5    157
2    152
0    151
9    150
1    146
Name: key, Length: 36, dtype: int64

In [36]:
pd.read_csv('examples/ex6.csv', nrows=5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

In [37]:
chunker = pd.read_csv('examples/ex6.csv', chunksize=1000)
chunker

In [38]:
chunker = pd.read_csv('examples/ex6.csv', chunksize=1000)

tot = pd.Series([])
for piece in chunker:
    tot = tot.add(piece['key'].value_counts(), fill_value=0)

tot = tot.sort_values(ascending=False)

In [40]:
tot

E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
     ...
5    157.0
2    152.0
0    151.0
9    150.0
1    146.0
Length: 36, dtype: float64

In [39]:
tot[:10]

E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

### Writing Data to Text Format
* data.to_csv('out.csv', index=False)

In [83]:
data = pd.read_csv('examples/ex5.csv')
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [84]:
data.to_csv('examples/out.csv') #seperator  ,
!cat examples/out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

Other delimiters can be used, of course (writing to sys.stdout so it prints the text
result to the console):

In [85]:
import sys
data.to_csv(sys.stdout, sep='|') #seperator |

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [86]:
# Missing values appear as empty strings in the output. You might want to denote them
# by some other sentinel value:
data.to_csv(sys.stdout, na_rep='NULL')

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [87]:
data.to_csv(sys.stdout, index=False, header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [88]:
data.to_csv(sys.stdout, index=False, columns=['a', 'b', 'c'])

a,b,c
1,2,3.0
5,6,
9,10,11.0

In [96]:
dates = pd.date_range('1/1/2000', periods=7)
dates

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07'],
              dtype='datetime64[ns]', freq='D')

In [97]:
ts = pd.Series(np.arange(7), index=dates)
ts

2000-01-01    0
2000-01-02    1
2000-01-03    2
2000-01-04    3
2000-01-05    4
2000-01-06    5
2000-01-07    6
Freq: D, dtype: int64

In [98]:
ts.to_csv('examples/tseries.csv')

/home/ys/anaconda3/envs/py37/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  """Entry point for launching an IPython kernel.

In [99]:
!cat examples/tseries.csv

2000-01-01,0
2000-01-02,1
2000-01-03,2
2000-01-04,3
2000-01-05,4
2000-01-06,5
2000-01-07,6

### Working with Delimited Formats

In [100]:
!cat examples/ex7.csv

"a","b","c"
"1","2","3"
"1","2","3"

In [106]:
import csv
f = open('examples/ex7.csv')

reader = csv.reader(f)
reader

In [102]:
for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [103]:
with open('examples/ex7.csv') as f:
    lines = list(csv.reader(f))
    
# from csv import reader
# with open('examples/ex7.csv') as file:
#     csv_reader = reader(file)
#     lines = list(csv_reader)

In [104]:
header, values = lines[0], lines[1:]

In [108]:
#test
header

['a', 'b', 'c']

In [118]:
#test
print("values  : ",values)
print("*values : ",*values)
print("-----------------------------------")
print(zip(*values))
print("=====================================")
for element in zip(*values):
    print(element)

values  :  [['1', '2', '3'], ['1', '2', '3']]
*values :  ['1', '2', '3'] ['1', '2', '3']
-----------------------------------
<zip object at 0x7f28710e6af0>
=====================================
('1', '1')
('2', '2')
('3', '3')

In [105]:
data_dict = {h: v for h, v in zip(header, zip(*values))}
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [135]:
#test csv read # convert to Uppercase , then save.
from csv import reader, writer
with open('examples/ex7.csv') as file:
    csv_reader = reader(file)
    lines2 = list(csv_reader)
    header2, values2 = lines2[0], lines2[1:]

In [123]:
header2

['a', 'b', 'c']

In [124]:
values2

[['1', '2', '3'], ['1', '2', '3']]

In [133]:
data_dict2 = { h: v for h,v in zip(header2, zip(*values2))}
# data_dict2 =  [{h: v} for h,v in zip(header2, zip(*values2))] #[{'a': ('1', '1')}, {'b': ('2', '2')}, {'c': ('3', '3')}]
data_dict2

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

In [136]:
#test : read csv, convert to upper case then save as csv file
from csv import reader, writer
with open('examples/ex7.csv') as file:
    csv_reader = reader(file)

    with open('examples/ex7_out.csv','w') as file:
        csv_writer = writer(file)
        for line in csv_reader:
            csv_writer.writerow([x.upper() for x in line])

In [ ]:
#######test csv reader writer DictReader DictWriter##########

# from csv import writer, DictWriter
# print("---------- Version using writer--------")
# with open("cats3.csv", "w") as file:
#     csv_writer = writer(file)
#     csv_writer.writerow(["Name", "Age"])
#     csv_writer.writerow(["Blue", 3])
#     csv_writer.writerow(["Kitty", 1])

# print("## ----------Version using DictWriter-------")
# with open("cats33.csv", "w") as file:
# 	headers = ["Name", "Breed", "Age"]
# 	csv_writer = DictWriter(file, fieldnames=headers)
# 	csv_writer.writeheader()
# 	csv_writer.writerow({
# 		"Name": "Garfield",
# 		"Breed": "Orange Tabby",
# 		"Age": 10
# 	})

##########################
# print("####### DictReader, convert cm to in and DictWriter as new dict #####")
# from csv import DictReader, DictWriter

# def cm_to_in(cm):
#     return int(float(cm) * 0.393701)

# with open("test305.csv") as file:
#     csv_reader = DictReader(file) 
#     fighters = list(csv_reader)

# with open("test305_inches.csv", "w") as file:
#     headers = ("Name", "Country", "Height")
#     csv_writer = DictWriter(file, fieldnames=headers)
#     csv_writer.writeheader()

#     for f in fighters:
#         csv_writer.writerow({
#             "Name" : f["Name"],
#             "Country" : f["Country"],
#             "Height" : cm_to_in(f["Height (in cm)"])
#         })

To define a new format with a different
delimiter, string quoting convention, or line terminator, we define a simple subclass
of csv.Dialect :

In [137]:
class my_dialect(csv.Dialect):
    lineterminator = '\n'
    delimiter = ';'
    quotechar = '"'
    quoting = csv.QUOTE_MINIMAL

In [138]:
reader = csv.reader(f, dialect=my_dialect)

We can also give individual CSV dialect parameters as keywords to **csv.reader**
without having to define a subclass:

In [139]:
reader = csv.reader(f, delimiter='|')

In [141]:
with open('mydata.csv', 'w') as f:
    writer = csv.writer(f, dialect=my_dialect)
    writer.writerow(('one', 'two', 'three'))
    writer.writerow(('1', '2', '3'))
    writer.writerow(('4', '5', '6'))
    writer.writerow(('7', '8', '9'))

### JSON Data
* result = json.loads(obj)
* asjson = json.dumps(result)
* pd.read_json('examples/example.json')

In [17]:
import numpy as np
import pandas as pd

In [18]:
obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
              {"name": "Katie", "age": 38,
               "pets": ["Sixes", "Stache", "Cisco"]}]
}
"""

In [19]:
import json
result = json.loads(obj)
result

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [20]:
asjson = json.dumps(result)
asjson

'{"name": "Wes", "places_lived": ["United States", "Spain", "Germany"], "pet": null, "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]}, {"name": "Katie", "age": 38, "pets": ["Sixes", "Stache", "Cisco"]}]}'

In [21]:
siblings = pd.DataFrame(result['siblings'], columns=['name', 'age'])
siblings

    name  age
0  Scott   30
1  Katie   38

In [22]:
!cat examples/example.json

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

In [23]:
data = pd.read_json('examples/example.json')
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [24]:
print(data.to_json())

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

In [25]:
print(data.to_json(orient='records'))

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

**json.dumps** returns a JSON STRING:

In [126]:
import json

class Cat:
	def __init__(self, name, breed):
		self.name = name
		self.breed = breed
		
c = Cat("Charles", "Tabby")

# json.dumps returns a JSON STRING:

j1 = json.dumps(['foo', {'bar': ('baz', None, 1.0, 2)}])
print(j1)
# results in '["foo", {"bar": ["baz", null, 1.0, 2]}]'

j2 = json.dumps(c.__dict__)
print(j2)
# results in '{"name": "Charles", "breed": "Tabby"}'

["foo", {"bar": ["baz", null, 1.0, 2]}]
{"name": "Charles", "breed": "Tabby"}

#### To JSONPICKLE 'c' the cat:

``
with open("cat.json", "w") as file:
	frozen = jsonpickle.encode(c)
	file.write(frozen)
``

In [129]:
# !python3 -m pip install jsonpickle # installed!

In [138]:
## $ python3 -m pip install jsonpickle
import jsonpickle

class Cat:
	def __init__(self, name, breed):
		self.name = name
		self.breed = breed

c = Cat("Charles", "Tabby")

# To JSONPICKLE 'c' the cat:
with open("cat.json", "w") as file:
	frozen = jsonpickle.encode(c)
	file.write(frozen)

# To bring back 'c' the cat using JSONPICKLE
with open("cat.json", "r") as file:
	contents = file.read()
	unfrozen = jsonpickle.decode(contents)
	print(unfrozen)
	print(type(unfrozen)) #<class '__main__.Cat'>
	print(f"name is {unfrozen.name} and breed is {unfrozen.breed}")

<__main__.Cat object at 0x7fb71adb8550>
<class '__main__.Cat'>
name is Charles and breed is Tabby

In [131]:
!cat cat.json

{"breed": "Tabby", "name": "Charles", "py/object": "__main__.Cat"}

### XML and HTML: Web Scraping

```
(py37)$ conda install lxml
(py37)$ conda install -c anaconda beautifulsoup4
(py37)$ conda install -c anaconda html5lib

```
<pip install beautifulsoup4 html5lib>

**pandas.read_html()** function has a number of options, but by default it searches
for and attempts to parse all tabular data contained within ``<table> tags``. The result is
a **list of DataFrame objects**:

In [27]:
tables = pd.read_html('examples/fdic_failed_bank_list.html')

In [28]:
print(len(tables))
tables #list

1

[                             Bank Name             City  ST   CERT  \
 0                          Allied Bank         Mulberry  AR     91
 1         The Woodbury Banking Company         Woodbury  GA  11297
 2               First CornerStone Bank  King of Prussia  PA  35312
 3                   Trust Company Bank          Memphis  TN   9956
 4           North Milwaukee State Bank        Milwaukee  WI  20364
 ..                                 ...              ...  ..    ...
 542                 Superior Bank, FSB         Hinsdale  IL  32646
 543                Malta National Bank            Malta  OH   6629
 544    First Alliance Bank & Trust Co.       Manchester  NH  34264
 545  National State Bank of Metropolis       Metropolis  IL   3815
 546                   Bank of Honolulu         Honolulu  HI  21029

                    Acquiring Institution        Closing Date  \
 0                           Today's Bank  September 23, 2016
 1                            United Bank     August 19, 2016
 2    First-Citizens Bank & Trust Company         May 6, 2016
 3             The Bank of Fayette County      April 29, 2016
 4    First-Citizens Bank & Trust Company      March 11, 2016
 ..                                   ...                 ...
 542                Superior Federal, FSB       July 27, 2001
 543                    North Valley Bank         May 3, 2001
 544  Southern New Hampshire Bank & Trust    February 2, 2001
 545              Banterra Bank of Marion   December 14, 2000
 546                   Bank of the Orient    October 13, 2000

           Updated Date
 0    November 17, 2016
 1    November 17, 2016
 2    September 6, 2016
 3    September 6, 2016
 4        June 16, 2016
 ..                 ...
 542    August 19, 2014
 543  November 18, 2002
 544  February 18, 2003
 545     March 17, 2005
 546     March 17, 2005

 [547 rows x 7 columns]]

In [29]:
failures = tables[0]
print(type(failures))
failures.head()

<class 'pandas.core.frame.DataFrame'>

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [30]:
close_timestamps = pd.to_datetime(failures['Closing Date'])
close_timestamps

0     2016-09-23
1     2016-08-19
2     2016-05-06
3     2016-04-29
4     2016-03-11
         ...
542   2001-07-27
543   2001-05-03
544   2001-02-02
545   2000-12-14
546   2000-10-13
Name: Closing Date, Length: 547, dtype: datetime64[ns]

In [31]:
close_timestamps.dt

In [32]:
close_timestamps.dt.year

0      2016
1      2016
2      2016
3      2016
4      2016
       ...
542    2001
543    2001
544    2001
545    2000
546    2000
Name: Closing Date, Length: 547, dtype: int64

In [33]:
close_timestamps.dt.year.value_counts()

2010    157
2009    140
2011     92
2012     51
2008     25
2013     24
2014     18
2002     11
2015      8
2016      5
2004      4
2001      4
2007      3
2003      3
2000      2
Name: Closing Date, dtype: int64

#### Parsing XML with lxml.objectify
* Using lxml.objectify , we parse the file and get a reference to the root node of the
XML file with **getroot** :

```
from lxml import objectify
path = 'datasets/mta_perf/Performance_MNR.xml'
parsed = objectify.parse(open(path))
root = parsed.getroot()
```

```
data = []
skip_fields = ['PARENT_SEQ', 'INDICATOR_SEQ',
               'DESIRED_CHANGE', 'DECIMAL_PLACES']
for elt in root.INDICATOR:
    el_data = {}
    for child in elt.getchildren():
        if child.tag in skip_fields:
            continue
        el_data[child.tag] = child.pyval #make dictionary
    data.append(el_data)
```

```
perf = pd.DataFrame(data)
```
--------------------------------------------

```
from io import StringIO
tag = '<a href="http://www.google.com">Google</a>'
root = objectify.parse(StringIO(tag)).getroot()
```

```
<INDICATOR>
  <INDICATOR_SEQ>373889</INDICATOR_SEQ>
  <PARENT_SEQ></PARENT_SEQ>
  <AGENCY_NAME>Metro-North Railroad</AGENCY_NAME>
  <INDICATOR_NAME>Escalator Availability</INDICATOR_NAME>
  <DESCRIPTION>Percent of the time that escalators are operational
  systemwide. The availability rate is based on physical observations performed
  the morning of regular business days only. This is a new indicator the agency
  began reporting in 2009.</DESCRIPTION>
  <PERIOD_YEAR>2011</PERIOD_YEAR>
  <PERIOD_MONTH>12</PERIOD_MONTH>
  <CATEGORY>Service Indicators</CATEGORY>
  <FREQUENCY>M</FREQUENCY>
  <DESIRED_CHANGE>U</DESIRED_CHANGE>
  <INDICATOR_UNIT>%</INDICATOR_UNIT>
  <DECIMAL_PLACES>1</DECIMAL_PLACES>
  <YTD_TARGET>97.00</YTD_TARGET>
  <YTD_ACTUAL></YTD_ACTUAL>
  <MONTHLY_TARGET>97.00</MONTHLY_TARGET>
  <MONTHLY_ACTUAL></MONTHLY_ACTUAL>
</INDICATOR>
```

In [40]:
# !cat datasets/mta_perf/Performance_MNR.xml

In [35]:
from lxml import objectify

path = 'datasets/mta_perf/Performance_MNR.xml'
parsed = objectify.parse(open(path))
root = parsed.getroot()

In [36]:

data = []

skip_fields = ['PARENT_SEQ', 'INDICATOR_SEQ',
               'DESIRED_CHANGE', 'DECIMAL_PLACES']

# root.INDICATOR returns a generator yielding each <INDICATOR> XML element.
# For each record, we can populate a dict of tag names (like YTD_ACTUAL ) to data values
# (excluding a few tags):
for elt in root.INDICATOR:
    el_data = {}
    for child in elt.getchildren():
        if child.tag in skip_fields:
            continue
        el_data[child.tag] = child.pyval #make dictionary, named el_data {child.tag:child.pyval}
    data.append(el_data)import json

class Cat:
	def __init__(self, name, breed):
		self.name = name
		self.breed = breed
		
c = Cat("Charles", "Tabby")

# json.dumps returns a JSON STRING:

j = json.dumps(['foo', {'bar': ('baz', None, 1.0, 2)}])
# results in '["foo", {"bar": ["baz", null, 1.0, 2]}]'

j = json.dumps(c.__dict__)
# results in '{"name": "Charles", "breed": "Tabby"}'

In [37]:
perf = pd.DataFrame(data)
perf.head()

,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,INDICATOR_UNIT,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,%,95,96.9,95,96.9
1,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,%,95,96,95,95
2,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,%,95,96.3,95,96.9
3,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,%,95,96.8,95,98.3
4,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,%,95,96.6,95,95.8

In [38]:
# Consider an HTML link tag, which is also valid XML:
from io import StringIO
tag = '<a href="http://www.google.com">Google</a>'
root = objectify.parse(StringIO(tag)).getroot()

You can now access any of the fields (like href ) in the tag or the link text:

In [44]:
root

In [50]:
# root.get('a')

In [49]:
root.get('href')

'http://www.google.com'

In [47]:
root.text

'Google'

## Binary Data Formats
* frame.to_pickle('frame_pickle') : store as pickle format
* pd.read_pickle('frame_pickle')

In [51]:
frame = pd.read_csv('examples/ex1.csv')
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [53]:
frame.to_pickle('examples/frame_pickle')

In [54]:
pd.read_pickle('examples/frame_pickle')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [55]:
!rm examples/frame_pickle

### pickle an object: pickle.dump(blue, file)
``
blue = Cat("Blue", "Scottish Fold", "String")
with open("pets.pickle", "wb") as file:
	pickle.dump(blue, file) ``

In [124]:
#test 
import pickle
class Animal:
	def __init__(self, name, species):
		self.name = name
		self.species = species

	def __repr__(self):
		return f"{self.name} is a {self.species}"

	def make_sound(self, sound):
		print(f"this animal says {sound}")


class Cat(Animal):
	def __init__(self, name, breed, toy):
		super().__init__(name, species="Cat") # Call init on parent class
		self.breed = breed
		self.toy = toy

	def play(self):
		print(f"{self.name} plays with {self.toy}")


blue = Cat("Blue", "Scottish Fold", "String")


# To pickle an object:
print("---write pickle -> pickle.dump(class_instance, opened_file_with_wb)--")

with open("pets.pickle", "wb") as file:
	pickle.dump(blue, file)

# #To unpickle something:
print("== unpickle -> pickle.load(opened_file_with_rb)")
with open("pets.pickle", "rb") as file:
	zombie_blue = pickle.load(file)
	print(zombie_blue)
	print(zombie_blue.play())

---write pickle -> pickle.dump(class_instance, opened_file_with_wb)--
== unpickle -> pickle.load(opened_file_with_rb)
Blue is a Cat
Blue plays with String
None

**json.dumps(...)** returns a JSON STRING:

### Using HDF5 Format(Hierarchical Data Format)
* good choice for working with very large data‐
sets that don’t fit into memory, as you can efficiently read and write small sections of
much larger arrays.
* **HDFStore** class works like a **dict** and handles the low-level
details:
```
frame = pd.DataFrame({'a': np.random.randn(100)})
store = pd.HDFStore('mydata.h5')
store['obj1'] = frame
```
* store.put
```
store.put('obj2', frame, format='table')
store.select('obj2', where=['index >= 10 and index <= 15'])
store.close()
```
```
frame.to_hdf('mydata3.h5', 'obj3', format='table')
pd.read_hdf('mydata3.h5', 'obj3', where=['index < 5'])
```

In [91]:
frame = pd.DataFrame({'a': np.random.randn(100)})
frame

           a
0   0.738640
1  -0.073061
2   0.814472
3  -1.171892
4   0.173533
..       ...
95  0.688656
96 -0.433357
97 -0.258220
98 -1.391553
99  1.135153

[100 rows x 1 columns]

In [92]:
store = pd.HDFStore('mydata.h5')
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5

In [93]:
store['obj1'] = frame #work like dict
store['obj1_col'] = frame['a']
store

<class 'pandas.io.pytables.HDFStore'>
File path: mydata.h5

In [94]:
store['obj1']

           a
0   0.738640
1  -0.073061
2   0.814472
3  -1.171892
4   0.173533
..       ...
95  0.688656
96 -0.433357
97 -0.258220
98 -1.391553
99  1.135153

[100 rows x 1 columns]

In [95]:
#test
store['obj1_col']

0     0.738640
1    -0.073061
2     0.814472
3    -1.171892
4     0.173533
        ...
95    0.688656
96   -0.433357
97   -0.258220
98   -1.391553
99    1.135153
Name: a, Length: 100, dtype: float64

HDFStore supports two storage schemas, **'fixed' and 'table'** . The latter is generally
slower, but it supports query operations using a special syntax:

In [96]:
store.put('obj2', frame, format='table') #'table' - query support

In [97]:
store.select('obj2', where=['index >= 10 and index <= 15'])

           a
10  0.764957
11 -0.990892
12 -0.621878
13 -0.039998
14  0.316543
15  1.704499

In [98]:
store.close()

In [100]:
frame.to_hdf('mydata3.h5', 'obj3', format='table') #save to hdf
pd.read_hdf('mydata3.h5', 'obj3', where=['index < 5'])

          a
0  0.738640
1 -0.073061
2  0.814472
3 -1.171892
4  0.173533

In [102]:
import os
os.remove('mydata3.h5')

### Reading Microsoft Excel Files(using ExcelFile class or pandas.read_excel function.)
* xlsx  = pd.ExcelFile('...')
* frame = pd.read_excel(xlsx, 'Sheet1') #faster
---------
* frame = pd.read_excel('examples/ex1.xlsx', 'Sheet1') #slower
-------------
```
* option1  
writer = pd.ExcelWriter('examples/ex2.xlsx')
frame.to_excel(writer, 'Sheet1')
writer.save()

* option2
frame.to_excel('examples/ex2.xlsx')
```

In [105]:
#To use ExcelFile , create an instance by passing a path to an xls or xlsx file
xlsx = pd.ExcelFile('examples/ex1.xlsx') #faster
xlsx

In [104]:
#Data stored in a sheet can then be read into DataFrame with parse :
pd.read_excel(xlsx, 'Sheet1')

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

If you are reading multiple sheets in a file, then it is faster to create the **ExcelFile** ,
but you can also simply pass the filename to pandas.read_excel :

In [106]:
frame = pd.read_excel('examples/ex1.xlsx', 'Sheet1') #slower
frame

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [107]:
writer = pd.ExcelWriter('examples/ex2.xlsx')
frame.to_excel(writer, 'Sheet1')
writer.save()

In [108]:
frame.to_excel('examples/ex2.xlsx')

In [109]:
!rm examples/ex2.xlsx

## Interacting with Web APIs

In [110]:
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

In [122]:
data = resp.json()
print(len(data))
data

30

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31045',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31045/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31045/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31045/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/31045',
  'id': 550264026,
  'node_id': 'MDExOlB1bGxSZXF1ZXN0MzYzMjAxMzk5',
  'number': 31045,
  'title': 'TST: Disallow bare pytest.raises',
  'user': {'login': 'gdex1',
   'id': 40249442,
   'node_id': 'MDQ6VXNlcjQwMjQ5NDQy',
   'avatar_url': 'https://avatars0.githubusercontent.com/u/40249442?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/gdex1',
   'html_url': 'https://github.com/gdex1',
   'followers_url': 'https://api.github.com/users/gdex1/followers',
   'following_url': 'https://api.github.com/users/gdex1/following{/other_user}',
   'gists_url': 'https://api.github.com/users/gdex1/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/gdex1/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/gdex1/subscriptions',
   'organizations_url': 'https://api.github.com/users/gdex1/orgs',
   'repos_url': 'https://api.github.com/users/gdex1/repos',
   'events_url': 'https://api.github.com/users/gdex1/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/gdex1/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2020-01-15T15:38:54Z',
  'updated_at': '2020-01-15T16:04:21Z',
  'closed_at': None,
  'author_association': 'NONE',
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/31045',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/31045',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/31045.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/31045.patch'},
  'body': '- [ ] ref #30999 \r\n- [ ] tests added / passed\r\n- [ ] passes `black pandas`\r\n- [ ] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`\r\n- [ ] whatsnew entry\r\n\r\nThis pull request is to add appropriate match arguments to bare pytest.raises listed in the comment https://github.com/pandas-dev/pandas/issues/30999#issuecomment-574174389 as described by the referenced issue.'},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31043',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31043/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31043/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31043/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/31043',
  'id': 550197014,
  'node_id': 'MDU6SXNzdWU1NTAxOTcwMTQ=',
  'number': 31043,
  'title': 'BUG: nonexistent Timestamp pre-summer/winter DST change with dateutil timezone',
  'user': {'login': 'AlexKirko',
   'id': 23253999,
   'node_id': 'MDQ6VXNlcjIzMjUzOTk5',
   'avatar_url': 'https://avatars1.githubusercontent.com/u/23253999?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/AlexKirko',
   'html_url': 'https://github.com/AlexKirko',
   'followers_url': 'https://api.github.com/users/AlexKirko/followers',
   'following_url': 'https://api.github.com/users/AlexKirko/following{/other_user}',
   'gists_url': 'https://api.github.com/users/AlexKirko/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/AlexKirko/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/AlexKirko/subscriptions',
   'organizations_url': 'https://api.github.com/users/AlexKirko/orgs',
   'repos_url': 'https://api.github.com/users/AlexKirko/repos',
   'events_url': 'https://api.github.com/users/AlexKirko/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/AlexKirko/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 2,
  'created_at': '2020-01-15T13:48:10Z',
  'updated_at': '2020-01-15T16:19:50Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'body': "#### Code Sample, a copy-pastable example if possible\r\n\r\nThis is fine:\r\n```\r\n>>> pd.__version__\r\n'0.26.0.dev0+1790.gdd94e0db9'\r\n>>> epoch =  1552211999999999871\r\n>>> t = pd.Timestamp(epoch, tz='dateutil/US/Pacific')\r\n>>> t\r\nTimestamp('2019-03-10 01:59:59.999999871-0800', tz='dateutil/US/Pacific')\r\n>>> t.value\r\n1552211999999999871\r\n>>> pd.Timestamp(t)\r\nTimestamp('2019-03-10 01:59:59.999999871-0800', tz='dateutil/US/Pacific')\r\n>>> pd.Timestamp(t).value\r\n1552211999999999871\r\n```\r\nThis is also fine:\r\n```\r\n>>> epoch =  1552212000000000000\r\n>>> t = pd.Timestamp(epoch, tz='dateutil/US/Pacific')\r\n>>> t\r\nTimestamp('2019-03-10 03:00:00-0700', tz='dateutil/US/Pacific')\r\n>>>\r\n>>> t.value\r\n1552212000000000000\r\n>>> pd.Timestamp(t)\r\nTimestamp('2019-03-10 03:00:00-0700', tz='dateutil/US/Pacific')\r\n>>> pd.Timestamp(t).value\r\n1552212000000000000\r\n```\r\nMeanwhile, this breaks representation and gets us nonexistent times:\r\n```\r\n>>> epoch =  1552211999999999872\r\n>>> t = pd.Timestamp(epoch, tz='dateutil/US/Pacific')\r\n>>> t\r\nTimestamp('2019-03-10 01:59:59.999999872-0700', tz='dateutil/US/Pacific')\r\n>>> t.value\r\n1552211999999999872\r\n>>> pd.Timestamp(t)\r\nTimestamp('2019-03-10 01:59:59.999999872-0800', tz='dateutil/US/Pacific')\r\n>>> pd.Timestamp(t).value\r\n1552208399999999872\r\n```\r\nAnd right on the cusp, the value breaks too:\r\n```\r\n>>> epoch =  1552211999999999999\r\n>>> t = pd.Timestamp(epoch, tz='dateutil/US/Pacific')\r\n>>> t\r\nTimestamp('2019-03-10 01:59:59.999999999-0700', tz='dateutil/US/Pacific')\r\n>>> t.value\r\n1552211999999999999\r\n>>> pd.Timestamp(t)\r\nTimestamp('2019-03-10 01:59:59.999999999-0800', tz='dateutil/US/Pacific')\r\n>>> pd.Timestamp(t).value\r\n1552208399999999999\r\n```\r\n\r\n#### Problem description\r\n\r\nWhen we use `dateutil` timezones and try to create a Timestamp that is right on the cusp of the change from winter to summer time, we can get nonexistent times (the clock is supposed to jump from 2 A.M. to 3 A.M. and yet we get 2:59:59).\r\n\r\nI've investigated this, and it appears that at 128 nanoseconds before the clock jump, DST offset and utcoffset in `dateutil` change, so we end up in a situation when the offsets are what they are supposed to be after the jump, but the time hasn't jumped yet, so the constructor returns a nonexistent time. Calling the constructor again moves the clock 1 hour back.\r\n\r\nThis can be checked out with:\r\n```\r\n>>> epoch =  1552211999999999872\r\n>>> t = pd.Timestamp(epoch, tz='dateutil/US/Pacific')\r\n>>> t.tz.dst(t)\r\ndatetime.timedelta(seconds=3600)\r\n```\r\n\r\nMy assumption is that when we need to determine UTC offset, rounding happens at some point, and we round to `epoch=1552212000000000000`, get offset, and then use it on time pre-clock jump.\r\n\r\nI'd like to try to fix this one.\r\n\r\n#### Expected Output\r\n```\r\n>>> epoch =  1552211999999999872\r\n>>> t = pd.Timestamp(epoch, tz='dateutil/US/Pacific')\r\n>>> t\r\nTimestamp('2019-03-10 01:59:59.999999872-0800', tz='dateutil/US/Pacific')\r\n>>> t.value\r\n1552211999999999872\r\n>>> pd.Timestamp(t)\r\nTimestamp('2019-03-10 01:59:59.999999872-0800', tz='dateutil/US/Pacific')\r\n>>> pd.Timestamp(t).value\r\n1552208399999999872\r\n```\r\n\r\n#### Notes\r\n\r\nThis was thought to be part of #24329 but turned to be a separate bug as I worked on closing that issue in PR #30995.\r\n\r\n#### Output of ``pd.show_versions()``\r\n\r\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : dd94e0db9556f35a3ea91ce85714c0b1e151a770\r\npython           : 3.7.6.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : ru_RU.UTF-8\r\nLOCALE           : None.None\r\n\r\npandas           : 0.26.0.dev0+1790.gdd94e0db9\r\nnumpy            : 1.17.4\r\npytz             : 2019.3\r\ndateutil         : 2.8.1\r\npip              : 19.3.1\r\nsetuptools       : 44.0.0.post20200106\r\nCython           : 0.29.14\r\npytest           : 5.3.2\r\nhypothesis       : 5.1.5\r\nsphinx           : 2.3.1\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : 1.2.7\r\nlxml.etree       : 4.4.2\r\nhtml5lib         : 1.0.1\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 2.10.3\r\nIPython          : 7.11.1\r\npandas_datareader: None\r\nbs4              : 4.8.2\r\nbottleneck       : 1.3.1\r\nfastparquet      : 0.3.2\r\ngcsfs            : None\r\nlxml.etree       : 4.4.2\r\nmatplotlib       : 3.1.2\r\nnumexpr          : 2.7.1\r\nodfpy            : None\r\nopenpyxl         : 3.0.1\r\npandas_gbq       : None\r\npyarrow          : 0.15.1\r\npytables         : None\r\npytest           : 5.3.2\r\ns3fs             : 0.4.0\r\nscipy            : 1.3.1\r\nsqlalchemy       : 1.3.12\r\ntables           : 3.6.1\r\ntabulate         : 0.8.6\r\nxarray           : 0.14.1\r\nxlrd             : 1.2.0\r\nxlwt             : 1.3.0\r\nxlsxwriter       : 1.2.7\r\nnumba            : 0.47.0\r\n\r\n</details>\r\n"},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31041',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31041/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31041/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31041/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/31041',
  'id': 550167966,
  'node_id': 'MDU6SXNzdWU1NTAxNjc5NjY=',
  'number': 31041,
  'title': 'BUG: something wrong at pd.Dataframe.from_dict()',
  'user': {'login': 'zhenghao0379',
   'id': 23721163,
   'node_id': 'MDQ6VXNlcjIzNzIxMTYz',
   'avatar_url': 'https://avatars2.githubusercontent.com/u/23721163?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/zhenghao0379',
   'html_url': 'https://github.com/zhenghao0379',
   'followers_url': 'https://api.github.com/users/zhenghao0379/followers',
   'following_url': 'https://api.github.com/users/zhenghao0379/following{/other_user}',
   'gists_url': 'https://api.github.com/users/zhenghao0379/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/zhenghao0379/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/zhenghao0379/subscriptions',
   'organizations_url': 'https://api.github.com/users/zhenghao0379/orgs',
   'repos_url': 'https://api.github.com/users/zhenghao0379/repos',
   'events_url': 'https://api.github.com/users/zhenghao0379/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/zhenghao0379/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 1465286368,
    'node_id': 'MDU6TGFiZWwxNDY1Mjg2MzY4',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Constructors',
    'name': 'Constructors',
    'color': 'd4c5f9',
    'default': False,
    'description': 'Series/DataFrame/Index/pd.array Constructors'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2020-01-15T12:52:35Z',
  'updated_at': '2020-01-15T13:40:57Z',
  'closed_at': None,
  'author_association': 'NONE',
  'body': '#### Code Sample, a copy-pastable example if possible\r\n\r\n```python\r\n# Your code here\r\nA = {"a":[1, 2, 3 ,4], "b":"b", "c":"c"}\r\npd.DataFrame.from_dict(A,orient=\'index\').T\r\n\r\nB = { "b":"b", "c":"c", "a":[1, 2, 3 ,4],}\r\npd.DataFrame.from_dict(B,orient=\'index\').T\r\n```\r\n#### Problem description\r\nthe output A ，B  are diffrent \r\n'},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31040',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31040/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31040/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31040/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/31040',
  'id': 550143379,
  'node_id': 'MDU6SXNzdWU1NTAxNDMzNzk=',
  'number': 31040,
  'title': 'DOC: Add CZI to the sponsors page',
  'user': {'login': 'datapythonista',
   'id': 10058240,
   'node_id': 'MDQ6VXNlcjEwMDU4MjQw',
   'avatar_url': 'https://avatars2.githubusercontent.com/u/10058240?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/datapythonista',
   'html_url': 'https://github.com/datapythonista',
   'followers_url': 'https://api.github.com/users/datapythonista/followers',
   'following_url': 'https://api.github.com/users/datapythonista/following{/other_user}',
   'gists_url': 'https://api.github.com/users/datapythonista/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/datapythonista/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/datapythonista/subscriptions',
   'organizations_url': 'https://api.github.com/users/datapythonista/orgs',
   'repos_url': 'https://api.github.com/users/datapythonista/repos',
   'events_url': 'https://api.github.com/users/datapythonista/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/datapythonista/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 134699,
    'node_id': 'MDU6TGFiZWwxMzQ2OTk=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs',
    'name': 'Docs',
    'color': '3465A4',
    'default': False,
    'description': None}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 1,
  'created_at': '2020-01-15T11:59:14Z',
  'updated_at': '2020-01-15T12:27:43Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'body': 'I guess we want to add CZI to the sponsors page: https://pandas.io/about/sponsors.html\r\n\r\nI think a section similar to Tidelift is the best option. Any other idea?'},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31039',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31039/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31039/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31039/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/31039',
  'id': 550131145,
  'node_id': 'MDU6SXNzdWU1NTAxMzExNDU=',
  'number': 31039,
  'title': 'CLN: Possibly obsolete scripts',
  'user': {'login': 'datapythonista',
   'id': 10058240,
   'node_id': 'MDQ6VXNlcjEwMDU4MjQw',
   'avatar_url': 'https://avatars2.githubusercontent.com/u/10058240?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/datapythonista',
   'html_url': 'https://github.com/datapythonista',
   'followers_url': 'https://api.github.com/users/datapythonista/followers',
   'following_url': 'https://api.github.com/users/datapythonista/following{/other_user}',
   'gists_url': 'https://api.github.com/users/datapythonista/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/datapythonista/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/datapythonista/subscriptions',
   'organizations_url': 'https://api.github.com/users/datapythonista/orgs',
   'repos_url': 'https://api.github.com/users/datapythonista/repos',
   'events_url': 'https://api.github.com/users/datapythonista/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/datapythonista/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 211029535,
    'node_id': 'MDU6TGFiZWwyMTEwMjk1MzU=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Clean',
    'name': 'Clean',
    'color': '207de5',
    'default': False,
    'description': None},
   {'id': 219960758,
    'node_id': 'MDU6TGFiZWwyMTk5NjA3NTg=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Discussion',
    'name': 'Needs Discussion',
    'color': '207de5',
    'default': False,
    'description': None}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 2,
  'created_at': '2020-01-15T11:32:30Z',
  'updated_at': '2020-01-15T12:31:56Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'body': "xref #31038\r\n\r\nI'm unsure if the following scripts are still used:\r\n```\r\nscripts/find_commits_touching_func.py\r\nci/check_cache.sh\r\nci/check_git_tags.sh\r\nci/travis_process_gbq_encryption.sh\r\n```\r\n\r\nThe next I assume are for the release, but may be there is something obsolete here:\r\n```\r\nscripts/build_dist_for_release.sh\r\nscripts/build_dist.sh\r\nscripts/download_wheels.py\r\n```"},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31038',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31038/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31038/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/31038/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/31038',
  'id': 550127653,
  'node_id': 'MDU6SXNzdWU1NTAxMjc2NTM=',
  'number': 31038,
  'title': 'CLN: Merge scripts/ and ci/ directories',
  'user': {'login': 'datapythonista',
   'id': 10058240,
   'node_id': 'MDQ6VXNlcjEwMDU4MjQw',
   'avatar_url': 'https://avatars2.githubusercontent.com/u/10058240?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/datapythonista',
   'html_url': 'https://github.com/datapythonista',
   'followers_url': 'https://api.github.com/users/datapythonista/followers',
   'following_url': 'https://api.github.com/users/datapythonista/following{/other_user}',
   'gists_url': 'https://api.github.com/users/datapythonista/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/datapythonista/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/datapythonista/subscriptions',
   'organizations_url': 'https://api.github.com/users/datapythonista/orgs',
   'repos_url': 'https://api.github.com/users/datapythonista/repos',
   'events_url': 'https://api.github.com/users/datapythonista/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/datapythonista/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 211029535,
    'node_id': 'MDU6TGFiZWwyMTEwMjk1MzU=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Clean',
    'name': 'Clean',
    'color': '207de5',
    'default': False,
    'description': None},
   {'id': 219960758,
    'node_id': 'MDU6TGFiZWwyMTk5NjA3NTg=',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Discussion',
    'name': 'Needs Discussion',
    'color': '207de5',
    'default': False,
    'description': None}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2020-01-15T11:24:32Z',
  'updated_at': '2020-01-15T11:32:16Z',
  'closed_at': None,
  'author_association': 'MEMBER',

In [121]:
data[0]['title']

'TST: Disallow bare pytest.raises'

In [123]:
issues = pd.DataFrame(data, columns=['number', 'title',
                                     'labels', 'state'])
issues.head()

,number,title,labels,state
0,31045,TST: Disallow bare pytest.raises,[],open
1,31043,BUG: nonexistent Timestamp pre-summer/winter D...,[],open
2,31041,BUG: something wrong at pd.Dataframe.from_dict(),"[{'id': 1465286368, 'node_id': 'MDU6TGFiZWwxND...",open
3,31040,DOC: Add CZI to the sponsors page,"[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...",open
4,31039,CLN: Possibly obsolete scripts,"[{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...",open

## Interacting with Databases
[SQLite keyword] https://www.sqlite.org/lang.html
```
$ sqlite3 ex1
SQLite version 3.28.0 2019-03-02 15:25:24
Enter ".help" for usage hints.
sqlite> create table tbl1(one varchar(10), two smallint);
sqlite> insert into tbl1 values('hello!',10);
sqlite> insert into tbl1 values('goodbye', 20);
sqlite> select * from tbl1;
hello!|10
goodbye|20
sqlite>
```
* a semicolon at the end of each SQL command!
```
sqlite> CREATE TABLE tbl2 (
   ...>   f1 varchar(30) primary key,
   ...>   f2 text,
   ...>   f3 real
   ...> );
sqlite>
```
54.  sqlite command line shell ; https://sqlite.org/cli.html
* SQLite will use a temporary database that is deleted when the session exits. To use a persistent disk file as the database, enter the ".open" command immediately after the terminal window starts up:
  *  database file named "ex1.db" to be opened and used. The "ex1.db" file is created if it does not previously exist. 
```
SQLite version 3.28.0 2019-03-02 15:25:24
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> .open ex1.db
sqlite>
```
* Alternatively, you can create a new database using the default temporary storage, then save that database into a disk file using the ".save" command:
  * Caution:".save" command as it will overwrite any preexisting database files having the same name without prompting for confirmation. As with the ".open" command, you might want to use a full pathname with forward-slash directory separators to avoid ambiguity.
```
SQLite version 3.28.0 2019-03-02 15:25:24
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> ... many SQL commands omitted ...
sqlite> .save ex1.db
sqlite
```

### create table and save
```
CREATE TABLE dogs (
    name TEXT,
    breed TEXT,
    age INTEGER
);
############ option1 #######command is capital !!###
$ sqlite3 test.sl3 
sqlite> create table dogs (name TEXT, breed TEXT, age INTEGER);
sqlite> insert into dogs values('Lews', 'Border Coli', 4);
sqlite> insert into dogs (name, breed, age) values('Lews1', 'Border Coli1', 10);
sqlite> insert into dogs values('Delma', 'Shepard', 9);
sqlite> select * from dogs;
.quit  #crtl + d

## no .save -> Now load the databse again.
$ sqlite3 test.sl3
sqlite> select * from dogs;   # shows result.

############## option2 #########
##sqlite> .save cats_db.db after creeate table.. for saving.
##sqlite> .backup main cats_db.db 
###################################
#$ sqlite3
sqllite> create table cats (name TEXT, breed TEXT, age INTEGER);
sqlite> insert into cats values('King', 'Persian', 2);
sqlite> insert into cats values('Kong', 'Boland', 5);
sqlite> .backup main cats_db.db
sqlite> .quit #ctrl _ db
###
$ sqlite3 cats_db.db
sqlite> .schema
sqlite> select * from cats_db.db;

############# option3 : .open 'Tweet_Data.db'#######
# Default for sqlite is to use transient in-memory db, But
# We will create db using sqlite> .open db_name.db
```

In [ ]:
#https://likegeeks.com/python-sqlite3-tutorial/
# https://www.sqlite.org/lang.html (sqlite keyword chart diaagram)

# create a connection object to connect us to the database
import sqlite3
con = sqlite3.connect('mydatabase.db')

#cursor object : method of the connection object. 
con = sqlite3.connect("mydatabase.db")
cursorObj = con.corsor()

## create db ##

import sqlite3
 
from sqlite3 import Error
 
def sql_connection():
 
    try:
 
        con = sqlite3.connect(':memory:')
 
        print("Connection is established: Database is created in memory")
 
    except Error:
 
        print(Error)
 
    finally:
 
        con.close()
 
sql_connection()

#Create Table
import sqlite3
 
from sqlite3 import Error
 
def sql_connection():
 
    try:
 
        con = sqlite3.connect('mydatabase.db')
 
        return con
 
    except Error:
 
        print(Error)
 
def sql_table(con):
 
    cursorObj = con.cursor()
 
    cursorObj.execute("CREATE TABLE employees(id integer PRIMARY KEY, name text, salary real, department text, position text, hireDate text)")
 
    con.commit()
 
con = sql_connection()
 
sql_table(con)

#insert table 1
cursorObj.execute("INSERT INTO employees VALUES(1, 'John', 700, 'HR', 'Manager', '2017-01-04')")
 
con.commit()

#insert table 2 - 

import sqlite3
 
con = sqlite3.connect('mydatabase.db')
 
def sql_insert(con, entities):
 
    cursorObj = con.cursor()
    
    cursorObj.execute('INSERT INTO employees(id, name, salary, department, position, hireDate) VALUES(?, ?, ?, ?, ?, ?)', entities)
    
    con.commit()
 
entities = (2, 'Andrew', 800, 'IT', 'Tech', '2018-02-06')
 
sql_insert(con, entities)

#update table
import sqlite3
 
con = sqlite3.connect('mydatabase.db')
 
def sql_update(con):
 
    cursorObj = con.cursor()
 
    cursorObj.execute('UPDATE employees SET name = "Rogers" where id = 2')
 
    con.commit()
 
sql_update(con)

#select 
cursorObj.execute('SELECT * FROM employees ')
cursorObj.execute('SELECT id, name FROM employees')

#Fetch all data 1
import sqlite3
 
con = sqlite3.connect('mydatabase.db')
 
def sql_fetch(con):
 
    cursorObj = con.cursor()
 
    cursorObj.execute('SELECT * FROM employees')
 
    rows = cursorObj.fetchall()
 
    for row in rows:
 
        print(row)
 
sql_fetch(con)

#Fetch all data 2
[print(row) for row in cursorObj.fetchall()]

#Fetch : fetch id and names of those who have a salary greater than 800
import sqlite3
 
con = sqlite3.connect('mydatabase.db')
 
def sql_fetch(con):
 
    cursorObj = con.cursor()
 
    cursorObj.execute('SELECT id, name FROM employees WHERE salary > 800.0')
 
    rows = cursorObj.fetchall()
 
    for row in rows:
 
        print(row)
 
sql_fetch(con)

#row count:  return the number of rows that are affected 
# or selected by the latest executed SQL query.
print(cursorObj.execute('SELECT * FROM employees').rowcount)


#row count 2 : 
# When we use rowcount with the SELECT statement, 
# -1 will be returned as how many rows are selected 
# is unknown until they are all fetched
#-> T'4 herefore, to get the row count, you need to fetch 
# all the data, and then get the length of the result
rows = cursorObj.fetchall()
 
print len (rows)

# list table
import sqlite3
 
con = sqlite3.connect('mydatabase.db')
 
def sql_fetch(con):
 
    cursorObj = con.cursor()
 
    cursorObj.execute('SELECT name from sqlite_master where type= "table"')
 
    print(cursorObj.fetchall())
 
sql_fetch(con)

#check if table exists or not
import sqlite3
 
con = sqlite3.connect('mydatabase.db')
 
def sql_fetch(con):
 
    cursorObj = con.cursor()
 
    cursorObj.execute('create table if not exists projects(id integer, name text)')
 
    con.commit()
 
sql_fetch(con)

#if table exits delete table
cursorObj.execute('drop table if exists projects')

#check if the table we want to access exists or not
cursorObj.execute('SELECT name from sqlite_master WHERE type = "table" AND name = "employees"')
 
print(cursorObj.fetchall())

# drop/delete a table using the DROP statement
import sqlite3
 
con = sqlite3.connect('mydatabase.db')
 
def sql_fetch(con):
 
    cursorObj = con.cursor()
 
    cursorObj.execute('DROP table if exists employees')
 
    con.commit()
 
sql_fetch(con)

In [113]:
import sqlite3
query = """
CREATE TABLE test
(a VARCHAR(20), b VARCHAR(20),
 c REAL,        d INTEGER
);"""
con = sqlite3.connect('mydata.sqlite')
con.execute(query)
con.commit()

In [114]:
data = [('Atlanta', 'Georgia', 1.25, 6),
        ('Tallahassee', 'Florida', 2.6, 3),
        ('Sacramento', 'California', 1.7, 5)]
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [115]:
cursor = con.execute('select * from test')
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [116]:
cursor.description
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [117]:
import sqlalchemy as sqla
db = sqla.create_engine('sqlite:///mydata.sqlite')
pd.read_sql('select * from test', db)

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [118]:
!rm mydata.sqlite

## Conclusion